# -*- coding: utf-8 -*-
"""FASTAI 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EMajU8gcD9QBvkiBlIy7KfbhGIRhSZ-T
"""

!pip install -U ddgs

from ddgs import DDGS #DuckDuckGo has changed the api so we need to update
from fastcore.all import *

def search_images(keywords, max_images=200):
  return L(DDGS().images(keywords, max_results=max_images)).itemgot('image')
import time, json

#NB: `search_images` depends on duckduckgo.com, which doesn't always return correct responses.
#    If you get a JSON error, just try running it again (it may take a couple of tries).
urls = search_images('pineapple photos', max_images=1)
urls[0]

from fastdownload import download_url
dest = 'pineapple.jpg'
download_url(urls[0], dest, show_progress=False)

from fastai.vision.all import *
im = Image.open(dest)
im.to_thumb(256,256)

download_url(search_images('dragonfruit photos', max_images=1)[0], 'dragonfruit.jpg', show_progress=False)
Image.open('dragonfruit.jpg').to_thumb(256,256)

searches = 'pineapple','dragonfruit'
path = Path('pineapple_or_not')

for o in searches:
    dest = (path/o)
    dest.mkdir(exist_ok=True, parents=True)
    download_images(dest, urls=search_images(f'{o} photo'))
    time.sleep(5)
    resize_images(path/o, max_size=400, dest=path/o)

failed = verify_images(get_image_files(path))
failed.map(Path.unlink)
len(failed)

dls = DataBlock(
    blocks=(ImageBlock, CategoryBlock),
    get_items=get_image_files,
    splitter=RandomSplitter(valid_pct=0.2, seed=42),
    get_y=parent_label,
    item_tfms=[Resize(192, method='squish')]
).dataloaders(path, bs=32)

learn = vision_learner(dls, resnet18, metrics=error_rate)
learn.fine_tune(3)

is_pineapple,_,probs = learn.predict(PILImage.create('pineapple.jpg'))
print(f"This is a: {is_pineapple}.")
print(f"Probability it's a pineapple: {probs[0]:.4f}")

